Fix memory safety issue
st-tech/Mockingjay pull request #1
Opened 2023-12-20 06:37 UTC by tosh7

2024-02-06 05:39 UTC, laprasdrum commented
@tosh7 こちらの判断に至ったBitriseのbuild linkをいただけますか？
> Xcode15に対応した際に、CI上でテスト実行時にクラッシュが観測されることがあった。
> 解析の結果MockingJayでクラッシュが起きている可能性が高く

2024-02-06 07:35 UTC, tosh7 commented
ちょっとBitriseで該当のログは見つからなかったのですが、
ローカルで発生していた時はこんな感じのログになっていました。
https://st-zozo.slack.com/archives/CDVDE8560/p1702640984283179

2024-02-06 08:07 UTC, tosh7 commented
Bitrise上で直近テスト実行時にクラッシュしているのだとここら辺ですね。
https://app.bitrise.io/build/3270bc54-c413-4c86-949b-80b6c23976b3?tab=log

↑ これに付随している問題かはログの詳しさ的に追えていませんんが。

2024-02-06 12:31 UTC, tosh7 commented
MockingJayがクラッシュする時のコンソールログ
```
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
```
![スクリーンショット 2024-02-06 21 29 39](https://github.com/st-tech/Mockingjay/assets/27297319/42fff061-f3da-462b-84bd-e81e31c3009a)

2024-02-06 12:44 UTC, tosh7 reviewed
自分が作成して、approveは出せないのでコメントで。
おそらくクラッシュ時のログを追っていると、stubs.reversed()した後ものに対して回している最中にindex out of rangeが走っている。
[ReversedCollection](https://developer.apple.com/documentation/swift/array/reversed())は新しいインスタンスを作成するわけではないので、参照している最中に別の書き込みが発生したとかが可能性としてはある気がします。
Xcode15から発生するようになった理由はテストの並列実行の仕組みの変化か何かとかはあるかもしれないと思いました。
修正方法としては、より安全に使用できるようにDispatchQueuenにつめて、意図しないアクセスを防いでいるのでこの修正方法は良さそうな気がしました。

2024-02-06 13:01 UTC, tosh7 commented
上記の過程に基づいて、このような修正を入れるだけでテストがこけないようになりました。
reversed()したものをmapすることで、新しくArrayのインスタンスが作られるのでこんな感じでやっても動作としては担保することができる。
```diff
--- a/Pods/Mockingjay/Sources/Mockingjay/MockingjayProtocol.swift
+++ b/Pods/Mockingjay/Sources/Mockingjay/MockingjayProtocol.swift
@@ -67,7 +67,7 @@ public class MockingjayProtocol: URLProtocol {
   /// This method searches backwards though the registered requests
   /// to find the last registered stub that handles the request.
   class func stubForRequest(_ request:URLRequest) -> Stub? {
-    for stub in stubs.reversed() {
+      for stub in stubs.reversed().map({ $0 }) {
       if stub.matcher(request) {
         return stub
       }
```

2024-02-13 02:32 UTC, laprasdrum requested changes
修正内容はこれでよさそうですが本家のindentは2なので合わせておきましょう

2024-02-13 02:32 UTC, laprasdrum commented on Sources/Mockingjay/MockingjayProtocol.swift
> +}
```suggestion
class MockingjayStorage {
  static let shared = MockingjayStorage()

  var stubs: [Stub] {
    get { accessQueue.sync { _stubs } }
    set { accessQueue.sync { _stubs = newValue } }
  }

  var registered: Bool {
    get { accessQueue.sync { _registered } }
    set { accessQueue.sync { _registered = newValue } }
  }

  private var _stubs = [Stub]()
  private var _registered: Bool = false
  private var accessQueue: DispatchQueue { DispatchQueue(label: "MockingjayStorageQueue", qos: .default) }
}
```

2024-02-13 02:32 UTC, laprasdrum commented on Sources/Mockingjay/MockingjayProtocol.swift
> +
```suggestion
  private class var storage: MockingjayStorage { .shared }
  private class var stubs: [Stub] {
    get { storage.stubs }
    set { storage.stubs = newValue }
  }
  private class var registered: Bool {
    get { storage.registered }
    set { storage.registered = newValue }
  }

```

2024-02-14 02:34 UTC, tosh7 commented
これは、他人のBranchなのでCommitを積めなさそう。

2024-02-14 02:35 UTC, laprasdrum commented
であれば仕方ないですがこのままmergeしましょうかね

2024-02-14 02:35 UTC, laprasdrum approved these changes

2024-02-14 02:36 UTC, merged